name: Update Homebrew

# Runs when receiving repository_dispatch event
on:
  repository_dispatch:
    types: [new_release]

jobs:
  update-homebrew:
    runs-on: ubuntu-latest
    steps:
      - name: Log trigger event
        run: |
          echo "Received repository_dispatch event"
          echo "Version from payload: ${{ github.event.client_payload.version }}"
      # Checkout your homebrew tap repository
      - name: Checkout tap
        uses: actions/checkout@v4
        with:
          repository: thewebAI/homebrew-webai
          token: ${{ secrets.RELEASE_TOKEN }}

      # Update formula with new version and SHA
      - name: Update formula
        env:
          VERSION: ${{ github.event.client_payload.version }}
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          echo "Starting formula update for version: ${VERSION}"

          # Get SHA256 values for each binary
          echo "Fetching SHA256 values from release assets..."

          # Fetch all assets info first
          ASSETS_JSON=$(gh release view $VERSION -R thewebAI/webai-cli-public --json assets)

          # Extract SHA256 values using jq for binaries
          ARM_SHA256=$(echo $ASSETS_JSON | jq -r '.assets[] | select(.name=="webai-darwin-arm64.sha256") | .url' | xargs curl -s -L | cut -d' ' -f1)
          INTEL_SHA256=$(echo $ASSETS_JSON | jq -r '.assets[] | select(.name=="webai-darwin-x64.sha256") | .url' | xargs curl -s -L | cut -d' ' -f1)
          LINUX_SHA256=$(echo $ASSETS_JSON | jq -r '.assets[] | select(.name=="webai-linux.sha256") | .url' | xargs curl -s -L | cut -d' ' -f1)

          # Validate SHA values
          if [ -z "$ARM_SHA256" ] || [ -z "$INTEL_SHA256" ] || [ -z "$LINUX_SHA256" ]; then
            echo "Error: Failed to fetch one or more SHA256 values"
            echo "Binary SHAs:"
            echo "ARM_SHA256: ${ARM_SHA256}"
            echo "INTEL_SHA256: ${INTEL_SHA256}"
            echo "LINUX_SHA256: ${LINUX_SHA256}"
            exit 1
          fi

          echo "ARM SHA256: ${ARM_SHA256}"
          echo "Intel SHA256: ${INTEL_SHA256}"
          echo "Linux SHA256: ${LINUX_SHA256}"

          # Update Version and SHA values in formula
          echo "Updating formula file..."
          # Update version line only
          sed -i "s|^  version \".*\"|  version \"${VERSION#v}\"|" Formula/webai.rb

          # Update SHA values only, leaving URLs unchanged
          sed -i "/on_arm do/,/end/ s|sha256 \"[^\"]*\"|sha256 \"${ARM_SHA256}\"|" Formula/webai.rb
          sed -i "/on_intel do/,/end/ s|sha256 \"[^\"]*\"|sha256 \"${INTEL_SHA256}\"|" Formula/webai.rb
          sed -i "/on_linux do/,/end/ s|sha256 \"[^\"]*\"|sha256 \"${LINUX_SHA256}\"|" Formula/webai.rb

          echo "Modified formula contents:"
          cat Formula/webai.rb

          # Commit and push changes
          echo "Committing and pushing changes..."
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add Formula/webai.rb
          git commit -m "webai: update to ${VERSION}"
          git push

          echo "Formula update completed successfully!"
